name: Move Jira Ticket

on:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${{ github.head_ref }})"
        id: extract_branch

      - name: Print slug/short variables
        run: |
          echo "Slug variables"
          echo " ref - ${{ github.ref }}"    
          echo " head_ref - ${{ github.head_ref }}"
          echo " base_ref - ${{ github.base_ref }}"
          echo " event - ${{ github.event }}"
          echo " event.name - ${{ github.event_name }}"
          echo " actor - ${{ github.actor }}"
          echo " workspace - ${{ github.workspace }}"
          echo " action - ${{ github.action }}"
          echo " sha - ${{ github.sha }}"
          echo " token - ${{ github.token }}"
          echo " token - ${{ github.token }}"
          echo " event.action - ${{ github.event.action }}"
          echo " event.number - ${{ github.event.number }}"
          echo " event.pull_request.state - ${{ github.event.pull_request.state }}"
          echo " event.pull_request.accept - ${{ github.event.pull_request.accept }}"
          echo " event.pull_request.owner - ${{ github.event.pull_request.owner }}"
          echo " event.pull_request.repo - ${{ github.event.pull_request.repo }}"
          echo " event.pull_request.head - ${{ github.event.pull_request.head }}"
          echo " event.pull_request.base - ${{ github.event.pull_request.base }}"
          echo " event.type - ${{ github.event.type }}"
          echo " event.pull_request.repo - ${{ github.pull_request.repo }}"
