# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print slug/short variables
        run: |
          echo "Slug variables"
          echo " - ${{ env.GITHUB_REF }}"    
          echo " - ${{ env.GITHUB_HEAD_REF }}"
          echo " - ${{ env.GITHUB_BASE_REF }}"
          echo " - ${{ env.GITHUB_REPOSITORY }}"
          // output e.g. : master feat-new-feature v1.0.0 product-1.0.0-rc.2 new-awesome-product
          echo "Slug URL variables"
          echo " - ${{ env.GITHUB_REF_URL }}"
          echo " - ${{ env.GITHUB_HEAD_REF_URL }}"
          echo " - ${{ env.GITHUB_BASE_REF_URL }}"
          echo " - ${{ env.GITHUB_REPOSITORY_URL }}"
          // output e.g. : master feat-new-feature v1-0-0 product-1-0-0-rc-2 new-awesome-product
          echo "Short SHA variables"
          echo " - ${{ env.GITHUB_SHA_SHORT }}"
          // output e.g. : ffac537e
