name: Move Jira Ticket

on:
  pull_request_review:
    types:
      - submitted

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print slug/short variables
        run: |
          echo "Slug variables"
          echo " - ${{ github.ref }}"    
          echo " - ${{ github.head_ref }}"
          echo " - ${{ github.base_ref }}"
          echo " - $(echo ${GITHUB_REF#refs/heads/})
          // output e.g. : master feat-new-feature v1.0.0 product-1.0.0-rc.2 new-awesome-product
          echo "Slug URL variables"
          echo " - ${GITHUB_REF_URL}"
          echo " - ${GITHUB_HEAD_REF_URL}"
          echo " - ${GITHUB_BASE_REF_URL}"
          echo " - ${GITHUB_REPOSITORY_URL }}"
          // output e.g. : master feat-new-feature v1-0-0 product-1-0-0-rc-2 new-awesome-product
          echo "Short SHA variables"
          echo " - ${GITHUB_SHA_SHORT}"
          // output e.g. : ffac537e